# Site settings
title: "Andy Hansen"
description: >
  A jumbled collection of thoughts

author: Andy Hansen
email: blog@andyhansen.co.nz
# twitter_username: AndyHecksen
github_username: andyhansen
instagram_username: andyhansen.nz
linkedin_username: hansenandy

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://andyhansen.co.nz" # the base hostname & protocol for your site

google_analytics_id: UA-91125210-1
# disqus_id: andyhansen

# Build settings
safe: false
include: [_pages]
exclude: [vendor]
markdown: kramdown
permalink: /posts/:title
collections:
  tags:
    output: true
    permalink: tags/:path/


timezone: Pacific/Auckland

sass:
    style: compressed

plugins:
  - jekyll-sitemap